print('"Hey User! Lets play a Madlib."')
print('.')
print('.')
print('.')
print('.')
Friend_name:str=input('Enter your friend name: ')
adjective:str=input('Enter any funny adjective(e.g weired, annoying,etc): ')
Animal_name:str=input('Enter name of any animal: ')
Object_name:str=input('Enter name of any random object(e.g,table, chair,etc): ')
body_part:str=input("Enter any part of body (e.g,Brain,head,Arms,legs,etc): ")
Food:str=input('Enter any food you like(e.g,pizza, burger,etc): ')
verb:str=input('Enter any random verb(e.g,study, laugh, read,etc): ')
insect:str=input('Enter any insect name in Plural(e.g,coackroaches, ants, bees, etc): ')
colour:str=input('Enter name of a colour: ')
planet:str=input('Enter any Planet Name(e.g,Mars,Jupiter,Neptune): ')
print('.')
print('.')
print('.')
print('.')
print(f'My Friend is seriously "{adjective}".')
print('.')
print(f'My friend {Friend_name} is the most {adjective} person I know.')
print(f"Yesterday, I caught him walking smoothly between the road with a {Object_name} placed on his head, upon asking he said that he was doing {body_part} exercise. {Friend_name} also thinks he can talk to {Animal_name}s and once tried to teach them how to {verb}.The worst part is that he refuses to eat anything except {Food} with roasted {insect} in it and drinks {colour} paint like it's a fancy juice.Despite that it's shocking to know that he never needs to visit the Hospital. I think he might be a {Animal_name} in his past life or he is an alien from {planet}.")
print(f'Previously I was saying that {Friend_name} is {adjective} but honestly, now I think that I am also {adjective} who has a friend like him.')
